### PR TITLE
simplify the abstract

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by marcblanchet** [comment]
closes #9

**Comment by avtobiff** [comment]
It would be good to have at least some of the motivation
why this work is needed in the abstract.

**Comment by boucadair** [comment]
Sure, assuming the motivation is accurate. The current text you have out there has many problems. 

Also, please note that documents such as RFC6242, have clear and concise abstract:

> 
> Abstract
> 
>    This document describes a method for invoking and running the Network
>    Configuration Protocol (NETCONF) within a Secure Shell (SSH) session
>    as an SSH subsystem.  This document obsoletes [RFC 4742](https://datatracker.ietf.org/doc/html/rfc4742).

**Comment by avtobiff** [comment]
@boucadair Indeed RFC 6242 is short. However, RFC 9250
has a longer abstract:

> This document describes the use of QUIC to provide transport confidentiality for DNS. The encryption provided by QUIC has similar properties to those provided by TLS, while QUIC transport eliminates the head-of-line blocking issues inherent with TCP and provides more efficient packet-loss recovery than UDP. DNS over QUIC (DoQ) has privacy properties similar to DNS over TLS (DoT) specified in RFC 7858, and latency characteristics similar to classic DNS over UDP. This specification describes the use of DoQ as a general-purpose transport for DNS and includes the use of DoQ for stub to recursive, recursive to authoritative, and zone transfer scenarios.

It helps giving some guidance to readers unaware of QUIC.

**Pull request merged**
